# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: '0'
  Minor: '0'
  Patch: '1'

steps:
- task: NuGetToolInstaller@0

- task: UseDotNet@2
  displayName: 'Use dotnet sdk 3.X'
  inputs:
    version: 3.x
    includePreviewVersions: false

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore from feed'
  inputs:
    command: restore
    projects: '**/RepoDb.SqlServer.sln'
    vstsFeed: 'VLB'
    includeNuGetOrg: true
    versioningScheme: byBuildNumber


- task: VSBuild@1
  inputs:
    solution: '**/RepoDb.SqlServer.sln'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '**/*.nuspec'
    includeSymbols: false
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'VLB'
    allowPackageConflicts: true